name: API CI with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Verify Docker Compose Version
        run: docker compose version

      - name: Build and Start Containers
        run: docker compose up -d --build

      - name: Wait for MySQL Service
        run: |
          for i in {1..30}; do
            if docker exec mysql mysqladmin ping -h "127.0.0.1" --silent; then
              echo "MySQL is up!"
              exit 0
            fi
            sleep 2
          done
          echo "MySQL did not start in time." >&2
          exit 1

      - name: Run PHPUnit Tests
        run: docker compose exec api php artisan test


      - name: Shutdown Containers
        if: always()
        run: docker compose down
