name: API CI without Docker

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    working-directory: api

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Ensure MySQL is installed and running
        run: |
          if ! command -v mysql >/dev/null 2>&1; then
            echo "MySQL not found. Installing MySQL Server..."
            sudo apt-get update
            sudo apt-get install -y mysql-server
          else
            echo "MySQL is already installed."
          fi
          echo "Starting MySQL service..."
          sudo service mysql start
          # Pause briefly to ensure MySQL is ready.
          sleep 5

      - name: Create Test Database
        run: |
          mysql -u root -e "CREATE DATABASE IF NOT EXISTS test_db;"
        env:
          MYSQL_PWD: ""

      - name: Run Laravel Migrations
        run: php artisan migrate --force

      - name: Run Tests
        run: ./vendor/bin/phpunit
